sudo: false
language: python
python:
  - "3.6"

env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py36
  - TOX_ENV=docs
  - TOX_ENV=py27-flake8
  - TOX_ENV=py36-flake8

install:
  - pip install -r requirements_dev.txt

script:
   - tox -e $TOX_ENV
