sudo: false
language: python
install:
  - pip install -r requirements_dev.txt

matrix:
  include:
    - python: 2.7
      env:
       - TOX_ENV=py27
       - TOX_ENV=py27-flake8
    - python: 3.6
      env:
        - TOX_ENV=py36
        - TOX_ENV=py36-flake8
        - TOX_ENV=docs
    - python: 3.7
      env:
        - TOX_ENV=py37

script: tox -e $TOX_ENV
